### ISSUE TITLE
Podtrac changes

### ISSUE THREAD

**Issue by KieranMcKeefery** [opawg/podcast-prefixes#1]
I think it would be better to have Podtrac under one line and just change the regex to:

`(dts|www|play)\.podtrac\.com`

Each line can be dedicated to the key prefix.

**Comment by jamescridland** [comment]
Yes, you’re not wrong. It isn’t built to use regexes, but I’ll go take a look at how that might work from a point of view of the codebase I’m using (selfishly) and see if it’s easier.


https://james.cridland.net • https://podnews.net
Tel: +61 447 692743

Amazingly Brilliant Pty Ltd

**Comment by jamescridland** [comment]
For now, since this isn't a regex, I'm going to close this comment to keep this clean. `SELECT DISTINCT` will do the job you're after.
